### ISSUE TITLE
Consider adding a `.quartoignore` file

### ISSUE THREAD

**Issue by davidwyld** [antarctica/basdoc#3]
I noticed in [this section](https://quarto.org/docs/extensions/formats.html#format-templates) of the quarto docs that for templates, most common repo files like `README.md`, `LICENSE` etc. won't be copied when using `quarto use template` but that others will.

When running `quarto use template` I noticed that it copies the `images/` directory from the repo, which looks to contain the example images and may not be the desired behaviour.

There's an option to include a `.quartoignore` file which could be use to exclude that directory, for example.

**Comment by thomaszwagerman** [comment]
Added, includes /images, *.Rproj, template.html - I believe those are all the files not strictly required
